### ISSUE TITLE
Changing the tab title

### ISSUE THREAD

**Issue by KevinKhau** [KevinKhau/five-card_draw_poker#2]
Can be done in `src/index.html`.
![image](https://user-images.githubusercontent.com/16297343/106313146-03837600-6268-11eb-99ae-092605eb68d9.png)

**Comment by Jwright707** [comment]
Hi @KevinKhau , I would like to tackle this issue 😀. If possible, what would you like the title to be changed to?

**Comment by KevinKhau** [comment]
Welcome @Jwright707 . "Five-card draw" looks good. 😄

**Comment by Jwright707** [comment]
Awesome, @KevinKhau just made the PR. 👍
